// <auto-generated />
namespace VRart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig4RemoveThumbNailFilePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4RemoveThumbNailFilePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201606052336093_mig4RemoveThumbNailFilePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
